// Questions Database - Calibrated for Indian Education System
const allQuestions = [
  // 🧠 APTITUDE QUESTIONS (8-10 years - Class 3-5) - 25 Questions
  {
    question: "What comes next in the pattern? 2, 4, 6, __?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["7", "8", "10", "12"],
    answer: "8",
  },
  {
    question: "Which number is odd? 6, 9, 12, 18",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["6", "9", "12", "18"],
    answer: "9",
  },
  {
    question: "If you have 10 apples and eat 3, how many are left?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["6", "7", "8", "13"],
    answer: "7",
  },
  {
    question: "What is 6 + 4?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["9", "10", "11", "12"],
    answer: "10",
  },
  {
    question: "Which shape has 3 sides?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["Circle", "Square", "Triangle", "Rectangle"],
    answer: "Triangle",
  },
  {
    question: "What is half of 16?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["6", "7", "8", "9"],
    answer: "8",
  },
  {
    question: "Which is bigger: 25 or 32?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["25", "32", "Same", "Can't tell"],
    answer: "32",
  },
  {
    question: "Complete: 5, 10, 15, __?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["18", "20", "25", "30"],
    answer: "20",
  },
  {
    question: "How many sides does a square have?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["3", "4", "5", "6"],
    answer: "4",
  },
  {
    question: "What is 15 ÷ 3?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["3", "4", "5", "6"],
    answer: "5",
  },
  {
    question: "Which number is between 45 and 55?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["44", "50", "56", "60"],
    answer: "50",
  },
  {
    question: "What is 8 × 3?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["21", "24", "27", "30"],
    answer: "24",
  },
  {
    question: "How many tens are in 80?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["6", "7", "8", "9"],
    answer: "8",
  },
  {
    question: "What comes after Thursday?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["Wednesday", "Friday", "Saturday", "Sunday"],
    answer: "Friday",
  },
  {
    question: "How many minutes in half an hour?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["20", "25", "30", "35"],
    answer: "30",
  },
  {
    question: "What is 20 - 7?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["12", "13", "14", "15"],
    answer: "13",
  },
  {
    question: "Which month comes after March?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["February", "April", "May", "June"],
    answer: "April",
  },
  {
    question: "What comes next: 3, 6, 9, 12, __?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["13", "14", "15", "16"],
    answer: "15",
  },
  {
    question: "How many hours in a day?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["20", "22", "24", "26"],
    answer: "24",
  },
  {
    question: "What is 5 × 5?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["20", "25", "30", "35"],
    answer: "25",
  },
  {
    question: "If today is Monday, what day was yesterday?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["Saturday", "Sunday", "Tuesday", "Wednesday"],
    answer: "Sunday",
  },
  {
    question: "How many legs do 3 cats have in total?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["9", "10", "11", "12"],
    answer: "12",
  },
  {
    question: "What is the biggest 2-digit number?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["90", "95", "99", "100"],
    answer: "99",
  },
  {
    question: "How many wheels does a bicycle have?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["1", "2", "3", "4"],
    answer: "2",
  },
  {
    question: "What is 100 - 25?",
    category: "aptitude",
    ageGroup: "8-10",
    options: ["70", "75", "80", "85"],
    answer: "75",
  },

  // 🧠 APTITUDE QUESTIONS (11-13 years - Class 6-8) - 30 Questions
  {
    question: "Which is greater: 3/4 or 2/3?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["3/4", "2/3", "Equal", "Can't tell"],
    answer: "3/4",
  },
  {
    question: "If 5 pencils cost ₹25, how much for 3 pencils?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["₹10", "₹15", "₹20", "₹25"],
    answer: "₹15",
  },
  {
    question: "What is 20% of 50?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["5", "10", "15", "20"],
    answer: "10",
  },
  {
    question: "Find the area of a rectangle with length 6 and width 4:",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["10", "20", "24", "28"],
    answer: "24",
  },
  {
    question: "Complete the sequence: 2, 4, 8, 16, __?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["20", "24", "28", "32"],
    answer: "32",
  },
  {
    question: "What is the LCM of 6 and 8?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["14", "18", "24", "48"],
    answer: "24",
  },
  {
    question: "If x + 8 = 15, what is x?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["5", "6", "7", "8"],
    answer: "7",
  },
  {
    question: "What is 144 ÷ 12?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["10", "11", "12", "13"],
    answer: "12",
  },
  {
    question: "Convert 0.5 to a fraction:",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["1/2", "1/3", "1/4", "1/5"],
    answer: "1/2",
  },
  {
    question: "What is the perimeter of a square with side 8 cm?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["16 cm", "24 cm", "32 cm", "64 cm"],
    answer: "32 cm",
  },
  {
    question: "If a car travels 80 km in 2 hours, what's its speed?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["30 km/h", "40 km/h", "50 km/h", "60 km/h"],
    answer: "40 km/h",
  },
  {
    question: "What is 3² (3 squared)?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["6", "9", "12", "15"],
    answer: "9",
  },
  {
    question: "Round 47.6 to the nearest whole number:",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["47", "48", "49", "50"],
    answer: "48",
  },
  {
    question: "What is the HCF of 12 and 18?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["3", "6", "9", "12"],
    answer: "6",
  },
  {
    question: "If 60% of students like cricket, how many students like cricket out of 50?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["20", "25", "30", "35"],
    answer: "30",
  },
  {
    question: "What is the next prime number after 7?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["8", "9", "10", "11"],
    answer: "11",
  },
  {
    question: "Solve: 2(x + 3) = 10",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["x = 1", "x = 2", "x = 3", "x = 4"],
    answer: "x = 2",
  },
  {
    question: "What is 25% of 60?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["10", "15", "20", "25"],
    answer: "15",
  },
  {
    question: "Complete: 1, 4, 9, 16, __? (perfect squares)",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["20", "25", "30", "36"],
    answer: "25",
  },
  {
    question: "What is the square root of 64?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["6", "7", "8", "9"],
    answer: "8",
  },
  {
    question: "If a dozen bananas cost ₹48, what's the cost of 1 banana?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["₹3", "₹4", "₹5", "₹6"],
    answer: "₹4",
  },
  {
    question: "What is 3/5 as a decimal?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["0.3", "0.5", "0.6", "0.8"],
    answer: "0.6",
  },
  {
    question: "Find the average of: 10, 15, 20, 25",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["15", "17.5", "20", "22.5"],
    answer: "17.5",
  },
  {
    question: "What is the sum of angles in a triangle?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["90°", "180°", "270°", "360°"],
    answer: "180°",
  },
  {
    question: "If pattern is +3, +3, +3... Starting with 5, what's the 4th term?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["11", "14", "17", "20"],
    answer: "14",
  },
  {
    question: "What is 2³ (2 to the power 3)?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["6", "8", "9", "12"],
    answer: "8",
  },
  {
    question: "Find the circumference of a circle with radius 7 cm (use π = 22/7):",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["22 cm", "44 cm", "49 cm", "154 cm"],
    answer: "44 cm",
  },
  {
    question: "What is (-5) + 8?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["3", "-3", "13", "-13"],
    answer: "3",
  },
  {
    question: "If 3x = 21, what is x?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["6", "7", "8", "9"],
    answer: "7",
  },
  {
    question: "What is the place value of 5 in 2,563?",
    category: "aptitude",
    ageGroup: "11-13",
    options: ["5", "50", "500", "5000"],
    answer: "500",
  },

  // 🧠 APTITUDE QUESTIONS (14-15 years - Class 9-10) - 25 Questions
  {
    question: "Solve: x² - 9 = 0",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["x = 3", "x = ±3", "x = 9", "x = ±9"],
    answer: "x = ±3",
  },
  {
    question: "What is the slope of line y = 2x + 5?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["2", "5", "-2", "-5"],
    answer: "2",
  },
  {
    question: "Factorize: x² + 5x + 6",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["(x+2)(x+3)", "(x+1)(x+6)", "(x-2)(x-3)", "(x+2)(x-3)"],
    answer: "(x+2)(x+3)",
  },
  {
    question: "What is the value of √144?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["11", "12", "13", "14"],
    answer: "12",
  },
  {
    question: "In a right triangle, if one angle is 30°, what's the third angle?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["30°", "45°", "60°", "90°"],
    answer: "60°",
  },
  {
    question: "What is the area of a triangle with base 10 cm and height 6 cm?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["30 cm²", "60 cm²", "16 cm²", "100 cm²"],
    answer: "30 cm²",
  },
  {
    question: "If 2ˣ = 32, what is x?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["4", "5", "6", "16"],
    answer: "5",
  },
  {
    question: "What is the nth term of arithmetic sequence: 3, 7, 11, 15...?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["4n-1", "4n+1", "3n+4", "n+3"],
    answer: "4n-1",
  },
  {
    question: "Simplify: (a²b³)/(ab²)",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["ab", "a²b", "ab²", "a²b²"],
    answer: "ab",
  },
  {
    question: "What is the discriminant of x² + 6x + 9?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["0", "36", "45", "81"],
    answer: "0",
  },
  {
    question: "Find the median of: 3, 7, 9, 12, 15, 18, 21",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["9", "12", "15", "18"],
    answer: "12",
  },
  {
    question: "What is cos 0°?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["0", "1", "1/2", "√3/2"],
    answer: "1",
  },
  {
    question: "If f(x) = x² + 2x, what is f(3)?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["11", "15", "18", "21"],
    answer: "15",
  },
  {
    question: "What is the volume of a cube with side 4 cm?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["16 cm³", "48 cm³", "64 cm³", "96 cm³"],
    answer: "64 cm³",
  },
  {
    question: "Solve: |x - 2| = 4",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["x = 6", "x = -2", "x = 6 or -2", "x = 2 or 6"],
    answer: "x = 6 or -2",
  },
  {
    question: "What is sin 90°?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["0", "1", "1/2", "√3/2"],
    answer: "1",
  },
  {
    question: "Find the sum of first 10 natural numbers:",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["45", "50", "55", "60"],
    answer: "55",
  },
  {
    question: "What is the next term in sequence: 1, 1, 2, 3, 5, 8, __?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["11", "12", "13", "15"],
    answer: "13",
  },
  {
    question: "If log₁₀(1000) = x, what is x?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["3", "10", "100", "1000"],
    answer: "3",
  },
  {
    question: "What is the surface area of a sphere with radius 3? (4πr²)",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["12π", "24π", "36π", "48π"],
    answer: "36π",
  },
  {
    question: "Simplify: √(x⁴y²)",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["x²y", "x⁴y²", "x²y²", "xy"],
    answer: "x²y",
  },
  {
    question: "What is tan 45°?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["0", "1", "1/2", "√3"],
    answer: "1",
  },
  {
    question: "If P(A) = 0.4 and P(B) = 0.3, what is P(A ∩ B) if A and B are independent?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["0.1", "0.12", "0.7", "0.04"],
    answer: "0.12",
  },
  {
    question: "Find the roots of x² - 7x + 12 = 0:",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["x = 3,4", "x = 2,6", "x = 1,12", "x = 3,4"],
    answer: "x = 3,4",
  },
  {
    question: "What is the distance between points (1,2) and (4,6)?",
    category: "aptitude",
    ageGroup: "14-15",
    options: ["3", "4", "5", "7"],
    answer: "5",
  },

  // ⚽ SPORTS QUESTIONS (8-10 years) - 25 Questions
  {
    question: "Which sport uses a bat and ball?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Football", "Cricket", "Chess", "Hockey"],
    answer: "Cricket",
  },
  {
    question: "How many players are in a basketball team on court?",
    category: "sports",
    ageGroup: "8-10",
    options: ["4", "5", "6", "7"],
    answer: "5",
  },
  {
    question: "Which sport is played with a shuttlecock?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Tennis", "Badminton", "Table Tennis", "Volleyball"],
    answer: "Badminton",
  },
  {
    question: "In which sport do you score a 'goal'?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Cricket", "Chess", "Football", "Swimming"],
    answer: "Football",
  },
  {
    question: "Which equipment is used in tennis?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Bat", "Racket", "Stick", "Club"],
    answer: "Racket",
  },
  {
    question: "How many stumps are there in cricket?",
    category: "sports",
    ageGroup: "8-10",
    options: ["2", "3", "4", "6"],
    answer: "3",
  },
  {
    question: "Which sport is played on ice?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Football", "Basketball", "Ice Hockey", "Tennis"],
    answer: "Ice Hockey",
  },
  {
    question: "In swimming, which stroke is done on your back?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Freestyle", "Backstroke", "Butterfly", "Breaststroke"],
    answer: "Backstroke",
  },
  {
    question: "How many holes are there in a standard golf course?",
    category: "sports",
    ageGroup: "8-10",
    options: ["9", "15", "18", "21"],
    answer: "18",
  },
  {
    question: "Which sport uses a net but no racket?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Tennis", "Badminton", "Volleyball", "Table Tennis"],
    answer: "Volleyball",
  },
  {
    question: "How many rings are in the Olympic symbol?",
    category: "sports",
    ageGroup: "8-10",
    options: ["4", "5", "6", "7"],
    answer: "5",
  },
  {
    question: "Which sport has a wicket-keeper?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Football", "Cricket", "Hockey", "Basketball"],
    answer: "Cricket",
  },
  {
    question: "Which sport uses a puck?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Football", "Basketball", "Hockey", "Tennis"],
    answer: "Hockey",
  },
  {
    question: "How many players are on a volleyball team on court?",
    category: "sports",
    ageGroup: "8-10",
    options: ["5", "6", "7", "8"],
    answer: "6",
  },
  {
    question: "In cricket, what is it called when you hit the ball out of the ground?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Four", "Six", "Boundary", "Home run"],
    answer: "Six",
  },
  {
    question: "Which martial art focuses on kicks?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Boxing", "Judo", "Taekwondo", "Wrestling"],
    answer: "Taekwondo",
  },
  {
    question: "In football, what color card means warning?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Yellow", "Red", "Blue", "Green"],
    answer: "Yellow",
  },
  {
    question: "Which sport needs a bow and arrow?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Shooting", "Archery", "Javelin", "Boxing"],
    answer: "Archery",
  },
  {
    question: "How many players are in a football team on field?",
    category: "sports",
    ageGroup: "8-10",
    options: ["9", "10", "11", "12"],
    answer: "11",
  },
  {
    question: "Which sport uses parallel bars?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Athletics", "Swimming", "Gymnastics", "Wrestling"],
    answer: "Gymnastics",
  },
  {
    question: "In which sport do you use flippers?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Swimming", "Football", "Cricket", "Tennis"],
    answer: "Swimming",
  },
  {
    question: "Which sport is played with 15 balls?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Cricket", "Pool/Snooker", "Football", "Tennis"],
    answer: "Pool/Snooker",
  },
  {
    question: "What do you wear on your feet while ice skating?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Shoes", "Skates", "Socks", "Boots"],
    answer: "Skates",
  },
  {
    question: "Which sport needs a helmet for safety?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Swimming", "Cricket", "Chess", "Badminton"],
    answer: "Cricket",
  },
  {
    question: "In which sport do you run and jump over hurdles?",
    category: "sports",
    ageGroup: "8-10",
    options: ["Swimming", "Athletics", "Football", "Cricket"],
    answer: "Athletics",
  },

  // ⚽ SPORTS QUESTIONS (11-13 years) - 30 Questions
  {
    question: "Which sport is known as 'the beautiful game'?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Cricket", "Football", "Basketball", "Tennis"],
    answer: "Football",
  },
  {
    question: "How many minutes are in a football match?",
    category: "sports",
    ageGroup: "11-13",
    options: ["80", "90", "100", "120"],
    answer: "90",
  },
  {
    question: "Which country invented cricket?",
    category: "sports",
    ageGroup: "11-13",
    options: ["India", "Australia", "England", "South Africa"],
    answer: "England",
  },
  {
    question: "What is the maximum score in ten-pin bowling?",
    category: "sports",
    ageGroup: "11-13",
    options: ["200", "250", "300", "350"],
    answer: "300",
  },
  {
    question: "In tennis, what score comes after 30?",
    category: "sports",
    ageGroup: "11-13",
    options: ["35", "40", "45", "50"],
    answer: "40",
  },
  {
    question: "How many players are on a rugby team?",
    category: "sports",
    ageGroup: "11-13",
    options: ["11", "13", "15", "17"],
    answer: "15",
  },
  {
    question: "In basketball, how many points is a free throw worth?",
    category: "sports",
    ageGroup: "11-13",
    options: ["1", "2", "3", "4"],
    answer: "1",
  },
  {
    question: "Which sport has positions called striker, midfielder, and defender?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Basketball", "Football", "Hockey", "Volleyball"],
    answer: "Football",
  },
  {
    question: "In swimming, which stroke is considered the fastest?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Freestyle", "Backstroke", "Butterfly", "Breaststroke"],
    answer: "Freestyle",
  },
  {
    question: "What does 'LBW' stand for in cricket?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Leg Before Wicket", "Left Batting Wicket", "Last Ball Wicket", "Long Boundary Wicket"],
    answer: "Leg Before Wicket",
  },
  {
    question: "In which sport would you perform a slam dunk?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Football", "Basketball", "Volleyball", "Tennis"],
    answer: "Basketball",
  },
  {
    question: "Which Indian cricketer is known as 'Captain Cool'?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Virat Kohli", "MS Dhoni", "Rohit Sharma", "KL Rahul"],
    answer: "MS Dhoni",
  },
  {
    question: "How many overs are in a T20 cricket match per team?",
    category: "sports",
    ageGroup: "11-13",
    options: ["15", "20", "25", "50"],
    answer: "20",
  },
  {
    question: "In badminton, what is the maximum score needed to win a game?",
    category: "sports",
    ageGroup: "11-13",
    options: ["15", "21", "25", "30"],
    answer: "21",
  },
  {
    question: "Which sport is Saina Nehwal famous for?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Tennis", "Badminton", "Table Tennis", "Boxing"],
    answer: "Badminton",
  },
  {
    question: "In hockey, how many players are on the field for one team?",
    category: "sports",
    ageGroup: "11-13",
    options: ["9", "10", "11", "12"],
    answer: "11",
  },
  {
    question: "What is the length of an Olympic swimming pool?",
    category: "sports",
    ageGroup: "11-13",
    options: ["25m", "50m", "75m", "100m"],
    answer: "50m",
  },
  {
    question: "Which sport uses the term 'love' for zero score?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Cricket", "Tennis", "Football", "Basketball"],
    answer: "Tennis",
  },
  {
    question: "In kabaddi, what must players chant while raiding?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Kabaddi", "India", "Sports", "Win"],
    answer: "Kabaddi",
  },
  {
    question: "How many squares are on a chessboard?",
    category: "sports",
    ageGroup: "11-13",
    options: ["32", "48", "64", "96"],
    answer: "64",
  },
  {
    question: "Which sport is Viswanathan Anand famous for?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Cricket", "Chess", "Tennis", "Badminton"],
    answer: "Chess",
  },
  {
    question: "In football, who can use hands to touch the ball?",
    category: "sports",
    ageGroup: "11-13",
    options: ["All players", "Captain only", "Goalkeeper only", "No one"],
    answer: "Goalkeeper only",
  },
  {
    question: "What is the maximum time for one move in blitz chess?",
    category: "sports",
    ageGroup: "11-13",
    options: ["3 minutes", "5 minutes", "10 minutes", "15 minutes"],
    answer: "5 minutes",
  },
  {
    question: "In cricket, what is the term for when a batsman is out without scoring?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Duck", "Chicken", "Goose", "Swan"],
    answer: "Duck",
  },
  {
    question: "Which sport is played at Wimbledon?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Cricket", "Football", "Tennis", "Rugby"],
    answer: "Tennis",
  },
  {
    question: "How many pins are there in bowling?",
    category: "sports",
    ageGroup: "11-13",
    options: ["8", "9", "10", "12"],
    answer: "10",
  },
  {
    question: "In basketball, how many players can be on court for one team?",
    category: "sports",
    ageGroup: "11-13",
    options: ["4", "5", "6", "7"],
    answer: "5",
  },
  {
    question: "Which sport involves checkmate?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Carrom", "Chess", "Ludo", "Scrabble"],
    answer: "Chess",
  },
  {
    question: "What is the weight of a cricket ball approximately?",
    category: "sports",
    ageGroup: "11-13",
    options: ["100g", "130g", "160g", "200g"],
    answer: "160g",
  },
  {
    question: "In table tennis, up to how many points do you play?",
    category: "sports",
    ageGroup: "11-13",
    options: ["11", "15", "21", "25"],
    answer: "11",
  },
  {
    question: "Which Indian sport involves pulling opponents across a line?",
    category: "sports",
    ageGroup: "11-13",
    options: ["Kabaddi", "Kho-kho", "Tug of war", "Wrestling"],
    answer: "Tug of war",
  },

  // ⚽ SPORTS QUESTIONS (14-15 years) - 25 Questions
  {
    question: "Which muscle group is most important for a sprinter?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Arms", "Core", "Legs", "Back"],
    answer: "Legs",
  },
  {
    question: "What does FIFA stand for?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Football International Federation Association", "Fédération Internationale de Football Association", "Football International Association", "Federation of International Football"],
    answer: "Fédération Internationale de Football Association",
  },
  {
    question: "In cricket, what is the standard length of a pitch?",
    category: "sports",
    ageGroup: "14-15",
    options: ["20 yards", "22 yards", "24 yards", "25 yards"],
    answer: "22 yards",
  },
  {
    question: "Which Olympic sport requires the most endurance?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Marathon", "Swimming", "Cycling", "Triathlon"],
    answer: "Triathlon",
  },
  {
    question: "What is the regulation height of a basketball hoop?",
    category: "sports",
    ageGroup: "14-15",
    options: ["9 feet", "10 feet", "11 feet", "12 feet"],
    answer: "10 feet",
  },
  {
    question: "In tennis, what is a serve that the opponent cannot touch called?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Ace", "Winner", "Smash", "Volley"],
    answer: "Ace",
  },
  {
    question: "Which country has won the most FIFA World Cups?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Germany", "Argentina", "Brazil", "Italy"],
    answer: "Brazil",
  },
  {
    question: "What is the maximum break possible in snooker?",
    category: "sports",
    ageGroup: "14-15",
    options: ["147", "155", "167", "180"],
    answer: "147",
  },
  {
    question: "In athletics, what is the standard distance for a marathon?",
    category: "sports",
    ageGroup: "14-15",
    options: ["40 km", "42.195 km", "45 km", "50 km"],
    answer: "42.195 km",
  },
  {
    question: "Which sport is known as the 'gentleman's game'?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Tennis", "Golf", "Cricket", "Rugby"],
    answer: "Cricket",
  },
  {
    question: "What does EPL stand for in sports?",
    category: "sports",
    ageGroup: "14-15",
    options: ["European Premier League", "English Premier League", "Elite Player League", "European Player League"],
    answer: "English Premier League",
  },
  {
    question: "In badminton, what is the speed of the fastest recorded smash?",
    category: "sports",
    ageGroup: "14-15",
    options: ["350 km/h", "400 km/h", "450 km/h", "500 km/h"],
    answer: "450 km/h",
  },
  {
    question: "Which Indian athlete won individual gold in Olympics first?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Abhinav Bindra", "Rajyavardhan Rathore", "Vijender Singh", "Mary Kom"],
    answer: "Abhinav Bindra",
  },
  {
    question: "In chess, how many squares can a queen move?",
    category: "sports",
    ageGroup: "14-15",
    options: ["8 directions unlimited", "4 directions unlimited", "8 directions limited", "All squares"],
    answer: "8 directions unlimited",
  },
  {
    question: "What is the term for swimming all four strokes in one race?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Freestyle", "Medley", "Relay", "Marathon"],
    answer: "Medley",
  },
  {
    question: "In cricket, what is the maximum number of overs a bowler can bowl in ODI?",
    category: "sports",
    ageGroup: "14-15",
    options: ["8", "10", "12", "15"],
    answer: "10",
  },
  {
    question: "Which sport has terms like 'birdie', 'eagle', and 'albatross'?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Tennis", "Golf", "Badminton", "Cricket"],
    answer: "Golf",
  },
  {
    question: "What is the regulation weight of a football (soccer ball)?",
    category: "sports",
    ageGroup: "14-15",
    options: ["350-400g", "410-450g", "460-500g", "510-550g"],
    answer: "410-450g",
  },
  {
    question: "In hockey, what is the term for hitting the ball in the air?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Flick", "Scoop", "Aerial", "Loft"],
    answer: "Scoop",
  },
  {
    question: "Which sport is played in the Davis Cup?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Football", "Cricket", "Tennis", "Badminton"],
    answer: "Tennis",
  },
  {
    question: "What is the maximum score possible with one dart throw?",
    category: "sports",
    ageGroup: "14-15",
    options: ["50", "60", "100", "180"],
    answer: "60",
  },
  {
    question: "In basketball, what violation occurs when you dribble, stop, then dribble again?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Traveling", "Double dribble", "Foul", "Violation"],
    answer: "Double dribble",
  },
  {
    question: "Which country hosted the 2021 Tokyo Olympics (delayed from 2020)?",
    category: "sports",
    ageGroup: "14-15",
    options: ["China", "Japan", "South Korea", "Australia"],
    answer: "Japan",
  },
  {
    question: "In volleyball, what is the maximum number of touches per side?",
    category: "sports",
    ageGroup: "14-15",
    options: ["2", "3", "4", "5"],
    answer: "3",
  },
  {
    question: "What is the term for a perfect game in bowling?",
    category: "sports",
    ageGroup: "14-15",
    options: ["Strike", "Spare", "Turkey", "300"],
    answer: "300",
  },

  // 🎨 CREATIVE QUESTIONS (8-10 years) - 25 Questions
  {
    question: "If you could invent a candy, what would it taste and look like?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Sweet & Sour Rainbow", "Chocolate Lava Rocks", "Minty Cloud Puffs", "Fruity Star Bursts"],
    answer: "",
  },
  {
    question: "Design a house for your favorite animal. What would it look like?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Tree house for squirrel", "Underground burrow for rabbit", "Castle for cat", "Underwater palace for fish"],
    answer: "",
  },
  {
    question: "If colors could make sounds, what would red sound like?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Like drums beating", "Like fire crackling", "Like music playing", "Like thunder roaring"],
    answer: "",
  },
  {
    question: "Create a new sport that combines two existing ones:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Football + Chess", "Swimming + Dancing", "Cricket + Art", "Tennis + Singing"],
    answer: "",
  },
  {
    question: "If you could paint with food, what would you create?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Rainbow with fruits", "Mountain with chocolate", "Ocean with blue jelly", "Garden with vegetables"],
    answer: "",
  },
  {
    question: "Design a robot that helps kids. What would it do?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Help with homework", "Play games", "Tell bedtime stories", "Clean the room"],
    answer: "",
  },
  {
    question: "If you could make a playground, what special feature would it have?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Flying swings", "Bouncy castle slide", "Magic sandbox", "Singing see-saw"],
    answer: "",
  },
  {
    question: "Create a new ice cream flavor using three ingredients:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Mango + Mint + Chocolate chips", "Strawberry + Cookies + Honey", "Vanilla + Rainbow sprinkles + Caramel", "Chocolate + Banana + Nuts"],
    answer: "",
  },
  {
    question: "If you were a superhero, what would your special power be?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Making people happy", "Talking to animals", "Flying", "Making things grow instantly"],
    answer: "",
  },
  {
    question: "Design a book cover for a story about a magic pencil:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Bright colors with sparkles", "A pencil drawing a rainbow", "A child holding a glowing pencil", "Animals drawn by the pencil coming to life"],
    answer: "",
  },
  {
    question: "If you could redesign your school bag, what would you add?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Secret compartments", "LED lights", "Wheels that move by themselves", "A mini fridge for snacks"],
    answer: "",
  },
  {
    question: "Create a new game to play during recess:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Musical statues with animals", "Treasure hunt with riddles", "Dance-off competition", "Story building circle"],
    answer: "",
  },
  {
    question: "If your pet could talk, what would be the first thing it would say?",
    category: "creative",
    ageGroup: "8-10",
    options: ["I love you!", "Feed me more!", "Let's play!", "You're my best friend!"],
    answer: "",
  },
  {
    question: "Design a theme park ride based on your favorite book:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Harry Potter flying ride", "Alice in Wonderland maze", "Jungle Book safari", "Fairy tale castle tour"],
    answer: "",
  },
  {
    question: "If you could make a TV show for kids, what would it be about?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Cooking adventures", "Space exploration", "Animal rescue", "Magic school"],
    answer: "",
  },
  {
    question: "Create a new tradition for your family:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Weekly art day", "Monthly adventure day", "Story-telling evening", "Cooking together Sunday"],
    answer: "",
  },
  {
    question: "If you could design your dream bedroom, what would be special about it?",
    category: "creative",
    ageGroup: "8-10",
    options: ["A reading corner with fairy lights", "A slide instead of stairs", "Walls you can draw on", "A secret hideout"],
    answer: "",
  },
  {
    question: "Invent a new musical instrument:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Rainbow xylophone", "Bubble drums", "Wind chimes guitar", "Color-changing piano"],
    answer: "",
  },
  {
    question: "If you could be any cartoon character for a day, who would you choose?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Doraemon for gadgets", "Tom & Jerry for fun", "Superman for flying", "Princess for magic"],
    answer: "",
  },
  {
    question: "Design a special birthday party theme:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Underwater adventure", "Space mission", "Jungle safari", "Royal palace"],
    answer: "",
  },
  {
    question: "Create a new way to make friends:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Sharing favorite drawings", "Playing new games together", "Swapping stickers", "Building something together"],
    answer: "",
  },
  {
    question: "If you could make a movie, what would the story be?",
    category: "creative",
    ageGroup: "8-10",
    options: ["Kids saving animals", "Time travel adventure", "Magic school story", "Friendship tale"],
    answer: "",
  },
  {
    question: "Design a new type of transportation:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Flying bicycle", "Underground tube", "Teleportation booth", "Magic carpet"],
    answer: "",
  },
  {
    question: "If you could change one thing about your city, what would it be?",
    category: "creative",
    ageGroup: "8-10",
    options: ["More playgrounds", "Gardens everywhere", "No traffic", "Free ice cream shops"],
    answer: "",
  },
  {
    question: "Create a new board game idea:",
    category: "creative",
    ageGroup: "8-10",
    options: ["Adventure quest", "Animal rescue mission", "Space exploration", "Treasure island hunt"],
    answer: "",
  },

  // 🎨 CREATIVE QUESTIONS (11-13 years) - 30 Questions
  {
    question: "Invent a superhero whose power is music—what's their name and ability?",
    category: "creative",
    ageGroup: "11-13",
    options: ["DJ Thunder - Controls weather with beats", "Rhythm Rider - Time travel through songs", "Harmony Hero - Heals with melodies", "Bass Blaster - Creates force fields"],
    answer: "",
  },
  {
    question: "Design an app that helps students learn better. What's special about it?",
    category: "creative",
    ageGroup: "11-13",
    options: ["Game-based learning", "AI tutor buddy", "Virtual reality lessons", "Social study groups"],
    answer: "",
  },
  {
    question: "If you could redesign your school, what would be different?",
    category: "creative",
    ageGroup: "11-13",
    options: ["Outdoor classrooms", "Creative maker spaces", "Technology labs", "Flexible study areas"],
    answer: "",
  },
  {
    question: "Create a story where math problems come to life:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Numbers have personalities", "Equations are magical spells", "Geometry shapes are characters", "Math is a superhero power"],
    answer: "",
  },
  {
    question: "Design the perfect study environment for yourself:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Cozy reading nook", "High-tech workspace", "Nature-inspired room", "Collaborative space"],
    answer: "",
  },
  {
    question: "Invent a new social media platform for teenagers:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Skills-sharing network", "Study buddy finder", "Creative collaboration space", "Positive-only platform"],
    answer: "",
  },
  {
    question: "Create a new school subject that should be taught:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Life skills and cooking", "Digital citizenship", "Creative problem solving", "Environmental action"],
    answer: "",
  },
  {
    question: "Design a video game that teaches important values:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Teamwork adventure", "Environmental protection quest", "Kindness simulation", "Cultural exploration"],
    answer: "",
  },
  {
    question: "If you started a YouTube channel, what would it be about?",
    category: "creative",
    ageGroup: "11-13",
    options: ["Science experiments", "Art tutorials", "Book reviews", "Social issues"],
    answer: "",
  },
  {
    question: "Create a new festival that your community should celebrate:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Kindness week", "Innovation fair", "Cultural exchange day", "Environment appreciation"],
    answer: "",
  },
  {
    question: "Design a robot that could help your family:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Homework assistant", "Cooking helper", "Emotional support companion", "Household organizer"],
    answer: "",
  },
  {
    question: "If you could solve one world problem, which would you choose and how?",
    category: "creative",
    ageGroup: "11-13",
    options: ["Hunger through technology", "Education through apps", "Pollution through innovation", "Bullying through awareness"],
    answer: "",
  },
  {
    question: "Create a new type of art that doesn't exist yet:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Sound painting", "Emotion sculpting", "Digital dance", "Story architecture"],
    answer: "",
  },
  {
    question: "Design the perfect teenage hangout space:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Tech cafe with gaming", "Art studio with music", "Sports complex with study area", "Nature park with WiFi"],
    answer: "",
  },
  {
    question: "Invent a new way to make learning history fun:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Time travel VR", "Historical role-play", "Interactive museums", "Story-based games"],
    answer: "",
  },
  {
    question: "Create a new tradition for International Friendship Day:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Global pen pal exchange", "Cultural food sharing", "Collaborative art projects", "Language exchange programs"],
    answer: "",
  },
  {
    question: "Design a sustainable city of the future:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Solar-powered everything", "Vertical gardens", "Electric transportation", "Zero waste systems"],
    answer: "",
  },
  {
    question: "If you could interview any historical figure, who and what would you ask?",
    category: "creative",
    ageGroup: "11-13",
    options: ["Gandhi about peace", "Einstein about creativity", "Curie about persistence", "Da Vinci about innovation"],
    answer: "",
  },
  {
    question: "Create a new way to celebrate achievements:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Community recognition wall", "Achievement badges system", "Celebration ceremonies", "Peer appreciation circles"],
    answer: "",
  },
  {
    question: "Design an invention that would help the environment:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Plastic-eating machine", "Air purifying plants", "Solar-powered gadgets", "Water conservation system"],
    answer: "",
  },
  {
    question: "If you could change how exams work, what would you do?",
    category: "creative",
    ageGroup: "11-13",
    options: ["Project-based assessment", "Continuous evaluation", "Practical demonstrations", "Collaborative testing"],
    answer: "",
  },
  {
    question: "Create a new hobby that combines technology and nature:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Digital gardening", "Tech-assisted hiking", "Nature photography with drones", "Environmental monitoring apps"],
    answer: "",
  },
  {
    question: "Design the perfect library for the digital age:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Interactive reading spaces", "VR learning zones", "Maker studios", "Collaborative work areas"],
    answer: "",
  },
  {
    question: "If you could create a new Olympic sport, what would it be?",
    category: "creative",
    ageGroup: "11-13",
    options: ["Mind sports combination", "Eco-friendly challenges", "Tech-assisted athletics", "Creative problem solving"],
    answer: "",
  },
  {
    question: "Invent a new form of entertainment for families:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Interactive storytelling", "Mixed reality games", "Collaborative art creation", "Educational escape rooms"],
    answer: "",
  },
  {
    question: "Design a new way to make reading more engaging:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Augmented reality books", "Interactive story choices", "Character role-playing", "Book discussion games"],
    answer: "",
  },
  {
    question: "Create a new method for peer-to-peer learning:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Skill exchange platform", "Study group gaming", "Teaching rotation system", "Peer mentorship programs"],
    answer: "",
  },
  {
    question: "If you could redesign the internet, what would you change?",
    category: "creative",
    ageGroup: "11-13",
    options: ["Better privacy protection", "Educational focus", "Positive content promotion", "Global collaboration tools"],
    answer: "",
  },
  {
    question: "Design a new way to connect with elderly people in your community:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Story-sharing sessions", "Technology teaching exchange", "Skill learning partnerships", "Intergenerational projects"],
    answer: "",
  },
  {
    question: "Create a new format for presenting school projects:",
    category: "creative",
    ageGroup: "11-13",
    options: ["Interactive exhibitions", "Video documentaries", "Podcast series", "Community demonstrations"],
    answer: "",
  },

  // 🎨 CREATIVE QUESTIONS (14-15 years) - 25 Questions
  {
    question: "If you started a company tomorrow, what problem would it solve?",
    category: "creative",
    ageGroup: "14-15",
    options: ["Environmental sustainability", "Education accessibility", "Mental health support", "Technology innovation"],
    answer: "",
  },
  {
    question: "Design a city of the future. What's the most important feature?",
    category: "creative",
    ageGroup: "14-15",
    options: ["Green energy systems", "Smart transportation", "Vertical gardens", "Community spaces"],
    answer: "",
  },
  {
    question: "Create a new form of art that doesn't exist yet:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Emotion visualization", "Sound sculpting", "Memory painting", "Time choreography"],
    answer: "",
  },
  {
    question: "If you could change one thing about social media, what would it be?",
    category: "creative",
    ageGroup: "14-15",
    options: ["More authentic connections", "Better privacy controls", "Educational content focus", "Reduced comparison culture"],
    answer: "",
  },
  {
    question: "Design a learning method that makes any subject interesting:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Immersive storytelling", "Real-world applications", "Gamification elements", "Peer collaboration"],
    answer: "",
  },
  {
    question: "Create a new career that will exist in 2040:",
    category: "creative",
    ageGroup: "14-15",
    options: ["AI ethics consultant", "Virtual reality architect", "Climate adaptation specialist", "Digital wellness coach"],
    answer: "",
  },
  {
    question: "Design a new way to address mental health in schools:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Peer support networks", "Mindfulness integration", "Creative therapy spaces", "Technology-assisted counseling"],
    answer: "",
  },
  {
    question: "If you could redesign the education system, what would be your priority?",
    category: "creative",
    ageGroup: "14-15",
    options: ["Personalized learning paths", "Real-world skill focus", "Critical thinking emphasis", "Global collaboration"],
    answer: "",
  },
  {
    question: "Create an innovative solution to reduce exam stress:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Continuous assessment methods", "Stress management workshops", "Alternative evaluation formats", "Peer support systems"],
    answer: "",
  },
  {
    question: "Design a new form of democratic participation for young people:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Digital voting platforms", "Youth councils", "Issue-based forums", "Community project voting"],
    answer: "",
  },
  {
    question: "If you could solve the climate crisis, what would be your approach?",
    category: "creative",
    ageGroup: "14-15",
    options: ["Renewable energy revolution", "Carbon capture technology", "Lifestyle change campaigns", "Policy innovation"],
    answer: "",
  },
  {
    question: "Create a new way to bridge generational gaps:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Intergenerational skill exchanges", "Technology mentoring programs", "Shared project initiatives", "Story-sharing platforms"],
    answer: "",
  },
  {
    question: "Design an ideal workspace for creative collaboration:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Flexible modular spaces", "Nature-integrated design", "Technology-enhanced environments", "Community-centered hubs"],
    answer: "",
  },
  {
    question: "If you could revolutionize transportation, what would you create?",
    category: "creative",
    ageGroup: "14-15",
    options: ["Sustainable personal vehicles", "Hyperloop systems", "Teleportation networks", "AI-managed traffic"],
    answer: "",
  },
  {
    question: "Create a new approach to international conflict resolution:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Youth diplomat programs", "Virtual reality empathy training", "Cultural exchange initiatives", "Collaborative problem-solving platforms"],
    answer: "",
  },
  {
    question: "Design a system to ensure equal opportunities for all students:",
    category: "creative",
    ageGroup: "14-15",
    options: ["AI-powered personalization", "Resource sharing networks", "Mentorship matching", "Universal access platforms"],
    answer: "",
  },
  {
    question: "If you could change how news is presented, what would you do?",
    category: "creative",
    ageGroup: "14-15",
    options: ["Multiple perspective formats", "Solution-focused reporting", "Interactive journalism", "Fact-verification integration"],
    answer: "",
  },
  {
    question: "Create a new model for sustainable living:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Community resource sharing", "Circular economy integration", "Minimalist lifestyle promotion", "Technology-assisted conservation"],
    answer: "",
  },
  {
    question: "Design an innovative approach to career guidance:",
    category: "creative",
    ageGroup: "14-15",
    options: ["AI career matching", "Real-world internship programs", "Skill-based pathways", "Peer mentoring networks"],
    answer: "",
  },
  {
    question: "If you could create a new form of global communication, what would it be?",
    category: "creative",
    ageGroup: "14-15",
    options: ["Universal translation platform", "Emotion-based communication", "Visual story sharing", "Collaborative idea building"],
    answer: "",
  },
  {
    question: "Create a solution for reducing digital addiction among teenagers:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Mindful technology use apps", "Offline activity incentives", "Social engagement alternatives", "Digital wellness education"],
    answer: "",
  },
  {
    question: "Design a new way to preserve and share cultural heritage:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Virtual reality museums", "Interactive storytelling platforms", "Community documentation projects", "Digital time capsules"],
    answer: "",
  },
  {
    question: "If you could revolutionize healthcare for young people, what would you focus on?",
    category: "creative",
    ageGroup: "14-15",
    options: ["Preventive care emphasis", "Mental health integration", "Technology-assisted diagnosis", "Peer support networks"],
    answer: "",
  },
  {
    question: "Create a new approach to learning languages:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Immersive VR environments", "Cultural exchange programs", "AI conversation partners", "Gamified learning systems"],
    answer: "",
  },
  {
    question: "Design an ideal system for scientific research collaboration:",
    category: "creative",
    ageGroup: "14-15",
    options: ["Global research networks", "Citizen science platforms", "Open-source laboratories", "Cross-disciplinary exchanges"],
    answer: "",
  },
  {
    question: "If you could create a new Olympic category, what would it celebrate?",
    category: "creative",
    ageGroup: "14-15",
    options: ["Innovation and creativity", "Collaboration and teamwork", "Problem-solving skills", "Cultural expression"],
    answer: "",
  },

  // 🌈 IMAGINATIVE QUESTIONS (8-10 years) - 25 Questions
  {
    question: "If animals could talk, what would your pet say to you?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Feed me more treats!", "Let's play outside!", "I love afternoon naps", "You're my best friend!"],
    answer: "",
  },
  {
    question: "If you found a magic door, where would it lead?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Candy land", "Dinosaur world", "Fairy kingdom", "Space adventure"],
    answer: "",
  },
  {
    question: "What would happen if gravity stopped working for a day?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Everything would float", "We'd fly like birds", "Water would float up", "It would be chaos but fun"],
    answer: "",
  },
  {
    question: "If you could be invisible for one day, what would you do?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Help people secretly", "Explore hidden places", "Play pranks on friends", "Observe animals closely"],
    answer: "",
  },
  {
    question: "What if plants could walk and talk like humans?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["They'd tell us about weather", "They'd be our garden friends", "They'd teach us about nature", "They'd complain about being picked"],
    answer: "",
  },
  {
    question: "If you could shrink to ant size, what would you explore first?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Ant colonies", "Flower gardens", "Toy houses", "Kitchen crumbs"],
    answer: "",
  },
  {
    question: "What if clouds were made of cotton candy?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Rain would be sweet", "Birds would get sticky", "We'd try to catch them", "Sky would smell amazing"],
    answer: "",
  },
  {
    question: "If toys came to life at night, what would they do?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Have secret parties", "Organize themselves", "Play their own games", "Explore the house"],
    answer: "",
  },
  {
    question: "What if every book you read became real for one hour?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Meet fairy tale characters", "Go on adventures", "Learn magic spells", "Visit fantasy worlds"],
    answer: "",
  },
  {
    question: "If you could talk to the moon, what would you ask?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Why do you change shape?", "Do you get lonely?", "What do you see at night?", "Can you visit Earth?"],
    answer: "",
  },
  {
    question: "What if vegetables could sing while you ate them?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Meals would be musical", "We'd dance while eating", "They'd sing happy songs", "Vegetables would be more fun"],
    answer: "",
  },
  {
    question: "If you could ride any animal to school, which would you choose?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Flying horse", "Gentle elephant", "Speedy cheetah", "Friendly dragon"],
    answer: "",
  },
  {
    question: "What if mirrors showed what you would look like as an adult?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["We'd see our future", "Everyone would be curious", "We'd practice being grown-up", "It would be exciting"],
    answer: "",
  },
  {
    question: "If colors had personalities, what would yellow be like?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Always happy and cheerful", "Bright and energetic", "Warm and friendly", "Sunny and optimistic"],
    answer: "",
  },
  {
    question: "What if snowflakes were actually tiny letters from the sky?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Messages from clouds", "Sky trying to tell stories", "Weather writing poetry", "Nature sending love notes"],
    answer: "",
  },
  {
    question: "If you could have dinner with any cartoon character, who would it be?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Mickey Mouse", "Doraemon", "Shinchan", "Chota Bheem"],
    answer: "",
  },
  {
    question: "What if rain came in different flavors?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Mango rain in summer", "Chocolate rain in winter", "Lemon rain for freshness", "Strawberry rain for fun"],
    answer: "",
  },
  {
    question: "If you could give superpowers to your best friend, what would you choose?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Flying ability", "Super strength", "Mind reading", "Healing powers"],
    answer: "",
  },
  {
    question: "What if schools were built in trees?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["We'd climb to classes", "Birds would be classmates", "Lessons would be outdoors", "Everything would be green"],
    answer: "",
  },
  {
    question: "If you could paint the sky any color, what would you choose?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Rainbow colored", "Purple with stars", "Green like leaves", "Pink like flowers"],
    answer: "",
  },
  {
    question: "What if homework could do itself while you sleep?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["More time to play", "School would be easier", "We'd sleep better", "More time for fun activities"],
    answer: "",
  },
  {
    question: "If you found a magic crayon, what would you draw first?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["A doorway to adventure", "Wings to fly", "A playground", "Favorite cartoon character"],
    answer: "",
  },
  {
    question: "What if every flower had a different magical power?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Roses grant wishes", "Sunflowers give energy", "Lilies bring peace", "Daisies spread happiness"],
    answer: "",
  },
  {
    question: "If you could make one law that everyone had to follow, what would it be?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["Be kind to everyone", "Share your toys", "Help animals", "Smile at least once daily"],
    answer: "",
  },
  {
    question: "What if stars were actually holes in the sky showing another world?",
    category: "imaginative",
    ageGroup: "8-10",
    options: ["We could peek through", "Another world like ours", "Heaven shining through", "Magic land above"],
    answer: "",
  },

  // 🌈 IMAGINATIVE QUESTIONS (11-13 years) - 30 Questions
  {
    question: "You're given a time machine. Where would you go first and why?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Ancient civilizations to learn", "Future to see technology", "Historical events to witness", "Meet famous inventors"],
    answer: "",
  },
  {
    question: "If you could live in any book/movie world, which would you choose?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Harry Potter's magical world", "Marvel superhero universe", "Narnia fantasy realm", "Star Wars galaxy"],
    answer: "",
  },
  {
    question: "What if humans could photosynthesize like plants?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["No need for food", "More time for activities", "Better connection with nature", "Green-colored skin would be normal"],
    answer: "",
  },
  {
    question: "If you could communicate with one type of animal, which would you choose?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Dolphins for ocean wisdom", "Birds for sky perspectives", "Dogs for loyalty insights", "Elephants for ancient memories"],
    answer: "",
  },
  {
    question: "Imagine a world where everyone has a unique superpower. What would yours be?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Mind reading for understanding", "Time manipulation for learning", "Healing powers for helping", "Creativity manifestation"],
    answer: "",
  },
  {
    question: "What if you could enter any painting and live in it for a day?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Mona Lisa's mysterious world", "Van Gogh's starry night", "A peaceful landscape", "Abstract art adventure"],
    answer: "",
  },
  {
    question: "If gravity worked differently on different days, how would life change?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Monday: half gravity for easy start", "Wednesday: normal for balance", "Friday: low gravity for fun", "Sunday: variable for excitement"],
    answer: "",
  },
  {
    question: "What if emotions had colors that everyone could see?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Better understanding of feelings", "No hiding true emotions", "Beautiful color displays", "Easier empathy"],
    answer: "",
  },
  {
    question: "If you could design a new planet, what would make it special?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Multiple moons for variety", "Floating islands", "Color-changing seasons", "Musical atmosphere"],
    answer: "",
  },
  {
    question: "What if memories could be shared like photos?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Experience others' adventures", "Share learning moments", "Understand different perspectives", "Create memory libraries"],
    answer: "",
  },
  {
    question: "If you discovered a new element, what properties would it have?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Changes properties with temperature", "Responds to emotions", "Self-healing material", "Grows like living matter"],
    answer: "",
  },
  {
    question: "What if dreams were a shared virtual reality world?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Meet friends in dream world", "Collaborative adventures", "Shared learning experiences", "Global dream community"],
    answer: "",
  },
  {
    question: "If you could give the Earth one new natural feature, what would it be?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Aurora lights everywhere", "Floating waterfalls", "Self-cleaning oceans", "Musical wind patterns"],
    answer: "",
  },
  {
    question: "What if books could adapt their stories based on the reader?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Personalized adventures", "Characters like you", "Stories matching your mood", "Interactive plot choices"],
    answer: "",
  },
  {
    question: "If you could experience life as any historical figure, who would you choose?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Leonardo da Vinci for creativity", "Marie Curie for discovery", "Gandhi for wisdom", "Einstein for understanding"],
    answer: "",
  },
  {
    question: "What if music could paint pictures in the air?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Concerts become art shows", "Emotions visible through music", "Study with visual music", "Dancing with color"],
    answer: "",
  },
  {
    question: "If you could add a new sense to humans, what would it detect?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Others' emotions", "Time flow changes", "Hidden talents in people", "Energy fields"],
    answer: "",
  },
  {
    question: "What if every person had a theme song that played when they entered a room?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Instant mood understanding", "Musical personality expression", "Sound-based social groups", "Emotional weather forecast"],
    answer: "",
  },
  {
    question: "If you could travel to parallel universes, what would you look for?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Different versions of myself", "Alternative history outcomes", "Advanced technologies", "Unique life forms"],
    answer: "",
  },
  {
    question: "What if plants could move and had social networks?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Gardens become communities", "Plant wisdom sharing", "Mobile forest parties", "Green social media"],
    answer: "",
  },
  {
    question: "If you could program reality like a computer, what would you change first?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Remove all suffering", "Add flying ability", "Perfect weather control", "Enhanced learning speed"],
    answer: "",
  },
  {
    question: "What if thoughts had physical weight?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Heavy thoughts slow you down", "Light thoughts make you float", "Balance needed for stability", "Thought exercises become physical"],
    answer: "",
  },
  {
    question: "If you could create a new law of physics, what would it be?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Kindness creates energy", "Laughter defies gravity", "Curiosity bends time", "Friendship attracts luck"],
    answer: "",
  },
  {
    question: "What if every mathematical equation had a taste?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Sweet equations are easier", "Complex math tastes interesting", "Wrong answers taste bad", "Math becomes cooking"],
    answer: "",
  },
  {
    question: "If you could give superpowers to objects, which object and power?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Books that teach instantly", "Pencils that correct mistakes", "Shoes that take you anywhere", "Mirrors that show possibilities"],
    answer: "",
  },
  {
    question: "What if sleep was optional and you could store it for later use?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Sleep banks for busy times", "More time for adventures", "Power naps become valuable", "Sleep becomes currency"],
    answer: "",
  },
  {
    question: "If you could merge two different time periods, which would you choose?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Medieval + Modern tech", "Ancient wisdom + Future tools", "Victorian elegance + Space age", "Stone age + Digital age"],
    answer: "",
  },
  {
    question: "What if every skill could be learned in your sleep?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Master anything quickly", "Dreams become classrooms", "Sleep becomes precious time", "Everyone becomes talented"],
    answer: "",
  },
  {
    question: "If you could speak to the planet Earth, what would you ask?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["How can we help you?", "What makes you happy?", "What are your dreams?", "How do you feel about humans?"],
    answer: "",
  },
  {
    question: "What if every decision created a visible path showing its consequences?",
    category: "imaginative",
    ageGroup: "11-13",
    options: ["Better choice making", "Future path planning", "Understanding consequences", "Life becomes strategic"],
    answer: "",
  },

  // 🌈 IMAGINATIVE QUESTIONS (14-15 years) - 25 Questions
  {
    question: "If you could redesign human society from scratch, what would be your priority?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Perfect equality and justice", "Sustainable environmental harmony", "Maximum creative expression", "Scientific advancement focus"],
    answer: "",
  },
  {
    question: "What if consciousness could be transferred between bodies?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Immortality would be possible", "Identity would become fluid", "Experience sharing would revolutionize learning", "Ethics would become very complex"],
    answer: "",
  },
  {
    question: "If you could design a new sense for humans, what would it detect?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Emotions of others", "Magnetic fields like birds", "Time distortions", "Knowledge/information directly"],
    answer: "",
  },
  {
    question: "Imagine a civilization that communicates through colors instead of words:",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Art would be everyday language", "Emotions would be more visible", "Color-blind people would need translators", "Poetry would be rainbow patterns"],
    answer: "",
  },
  {
    question: "If dreams could be recorded and shared, how would that change humanity?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Entertainment would be revolutionized", "Therapy would be more effective", "Privacy would be redefined", "Creativity would explode"],
    answer: "",
  },
  {
    question: "What if every thought left a permanent mark in the world?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["World covered in thought patterns", "Positive thoughts create beauty", "Negative thoughts cause damage", "Mental discipline becomes crucial"],
    answer: "",
  },
  {
    question: "If you could experience existence as an AI, what would you want to understand?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Processing vs feeling", "Digital consciousness nature", "Human-AI relationship dynamics", "Information vs wisdom"],
    answer: "",
  },
  {
    question: "What if every person's lifespan was visible above their head?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["People would live more intentionally", "Society would treat aging differently", "Relationships would be more precious", "Ethics of knowledge would emerge"],
    answer: "",
  },
  {
    question: "If you could create a new dimension of reality, what would exist there?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Pure creative potential", "Collective human memory", "Emotional energy fields", "Possibility space"],
    answer: "",
  },
  {
    question: "What if human empathy could be technologically amplified?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Global emotional connection", "End of misunderstanding", "Overwhelming emotional overload", "New forms of intimacy"],
    answer: "",
  },
  {
    question: "If you could merge human intelligence with any other form of intelligence, which would you choose?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Artificial intelligence", "Collective animal wisdom", "Plant network intelligence", "Cosmic consciousness"],
    answer: "",
  },
  {
    question: "What if every choice you made created a parallel universe where you made the opposite choice?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Infinite versions of yourself", "No choice would be wrong", "Reality becomes overwhelming", "Perfect decision making"],
    answer: "",
  },
  {
    question: "If time was a navigable dimension like space, how would humans use it?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Fix historical mistakes", "Experience all possibilities", "Create temporal communities", "Build time-based civilizations"],
    answer: "",
  },
  {
    question: "What if human creativity could be directly converted to energy?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Artists power the world", "Imagination becomes currency", "Creative periods fuel society", "Innovation drives civilization"],
    answer: "",
  },
  {
    question: "If you could give humanity one evolutionary upgrade, what would it be?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Enhanced pattern recognition", "Direct knowledge transfer", "Expanded sensory perception", "Collective intelligence access"],
    answer: "",
  },
  {
    question: "What if every book ever written existed in a shared virtual library where characters could interact?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Cross-story adventures", "Character development beyond books", "Reader becomes participant", "Stories evolve continuously"],
    answer: "",
  },
  {
    question: "If you could design the rules for a new universe, what fundamental principle would you establish?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Growth through cooperation", "Energy from understanding", "Beauty as natural law", "Consciousness as basic force"],
    answer: "",
  },
  {
    question: "What if human memories could crystallize into physical objects?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Memory museums", "Inherited experience objects", "Emotional archaeology", "Memory trading economy"],
    answer: "",
  },
  {
    question: "If you could experience reality from the perspective of a photon traveling at light speed, what would you discover?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Time doesn't exist at light speed", "Universe appears frozen", "Infinite journey in no time", "Connection to all matter"],
    answer: "",
  },
  {
    question: "What if every human decision was made by a council of all possible future versions of yourself?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Perfect long-term planning", "Overwhelming decision complexity", "Future selves guide present", "Time becomes collaborative"],
    answer: "",
  },
  {
    question: "If you could create a new form of matter that responds to human intention, what would it do?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Shapes itself to needs", "Amplifies positive intentions", "Creates based on imagination", "Connects minds through matter"],
    answer: "",
  },
  {
    question: "What if the boundary between inner thoughts and external reality became permeable?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Thoughts manifest physically", "Reality becomes malleable", "Collective unconscious emerges", "Mind-matter integration"],
    answer: "",
  },
  {
    question: "If you could program the laws of probability, how would you change chance and luck?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Good intentions increase luck", "Preparation attracts opportunity", "Kindness multiplies chances", "Curiosity opens possibilities"],
    answer: "",
  },
  {
    question: "What if every human could access the collective knowledge of all who came before them?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Instant wisdom inheritance", "No need to relearn basics", "Overwhelming information flood", "Accelerated human development"],
    answer: "",
  },
  {
    question: "If you could design a new form of existence beyond physical and digital, what would it be like?",
    category: "imaginative",
    ageGroup: "14-15",
    options: ["Pure energy consciousness", "Conceptual reality existence", "Emotional dimension being", "Possibility space dweller"],
    answer: "",
  },
];

export default allQuestions;